"""Blackjack Coach Pro Demo.

Educational/practice blackjack basic-strategy tool. This package does NOT
connect to casinos, does NOT automate real-money betting, does NOT use any
camera/video at a real table, and makes NO promise of winnings.
See docs/PROJECT_RULES.md for the full project rules.
"""

from .counting import (
    CountingState,
    counting_summary,
    hilo_value,
    is_counting_allowed_context,
    true_count,
    update_running_count,
    update_running_count_many,
)
from .decision_diagnostics import DecisionDiagnostic, explain_decision_factors
from .deviations import (
    DEFAULT_DEVIATION_RULES,
    DeviationRecommendation,
    DeviationRule,
    compare_true_count,
    find_matching_deviation,
    normalize_true_count,
    recommend_with_deviation,
)
from .explanations import (
    ACTION_NOTES,
    explain_action,
    explain_insurance_no,
    explain_state,
)
from .formatting import (
    format_cards,
    format_header,
    format_kv,
    format_list,
    format_percentage,
    format_result_status,
    format_section,
    format_warning,
)
from .hand_evaluator import HandEvaluation, card_value, evaluate_hand, normalize_rank
from .quiz import (
    CountQuizResult,
    QuizQuestion,
    QuizResult,
    QuizSessionResult,
    build_strategy_questions,
    generate_strategy_question,
    grade_strategy_answer,
    normalize_user_action,
    run_count_session,
    run_strategy_session,
)
from .rules import (
    DEFAULT_PROFILE,
    DOUBLE_DECK_H17_DAS_NS,
    DOUBLE_DECK_S17_DAS_LS,
    EIGHT_DECK_H17_DAS_LS,
    EIGHT_DECK_S17_DAS_LS,
    FOUR_DECK_H17_DAS_LS,
    MULTI_DECK_H17_DAS_LS,
    MULTI_DECK_S17_DAS_LS,
    PROFILES,
    SINGLE_DECK_H17_NDAS_NS,
    SINGLE_DECK_S17_DAS_LS,
    SIX_DECK_H17_DAS_LS,
    SIX_DECK_S17_DAS_LS,
    RuleProfile,
    describe_rule_profile,
    get_profile,
    get_rule_profile,
    list_rule_profiles,
    normalize_profile_key,
    profile_supports_das,
    profile_supports_hit_split_aces,
    profile_supports_resplit,
    profile_supports_surrender,
)
from .session_history import (
    HistorySummary,
    SessionRecord,
    build_session_record,
    default_history_dir,
    ensure_history_dir,
    list_session_records,
    load_session_record,
    save_session_record,
    summarize_history,
)
from .shoe import (
    build_shoe,
    cards_remaining,
    decks_remaining,
    draw_card,
    penetration,
    shuffle_shoe,
    validate_decks,
)
from .simulator import (
    HandOutcome,
    PlayedHand,
    PlayedSplitHand,
    SimulatedHand,
    SplitSubHand,
    can_split_hand,
    deal_initial_hand,
    play_dealer_hand,
    play_split_subhand,
    play_training_hand,
    resolve_outcome,
    simulate_training_hand,
    split_initial_hand,
)
from .split_rules import (
    SplitRuleDecision,
    can_double_after_split,
    can_hit_split_aces,
    can_resplit,
    can_split_initial_hand,
    explain_split_rules,
    is_ace_pair,
    is_pair_hand,
)
from .strategy_engine import (
    Action,
    Recommendation,
    recommend,
    should_take_insurance,
)

__version__ = "1.8.0"

__all__ = [
    "ACTION_NOTES",
    "Action",
    "CountQuizResult",
    "CountingState",
    "DEFAULT_PROFILE",
    "DOUBLE_DECK_H17_DAS_NS",
    "DOUBLE_DECK_S17_DAS_LS",
    "DecisionDiagnostic",
    "DeviationRecommendation",
    "DeviationRule",
    "DEFAULT_DEVIATION_RULES",
    "EIGHT_DECK_H17_DAS_LS",
    "EIGHT_DECK_S17_DAS_LS",
    "FOUR_DECK_H17_DAS_LS",
    "HandEvaluation",
    "HandOutcome",
    "HistorySummary",
    "MULTI_DECK_H17_DAS_LS",
    "MULTI_DECK_S17_DAS_LS",
    "PROFILES",
    "PlayedHand",
    "PlayedSplitHand",
    "QuizQuestion",
    "QuizResult",
    "QuizSessionResult",
    "Recommendation",
    "RuleProfile",
    "SINGLE_DECK_H17_NDAS_NS",
    "SINGLE_DECK_S17_DAS_LS",
    "SIX_DECK_H17_DAS_LS",
    "SIX_DECK_S17_DAS_LS",
    "SessionRecord",
    "SimulatedHand",
    "SplitRuleDecision",
    "SplitSubHand",
    "build_session_record",
    "build_shoe",
    "build_strategy_questions",
    "can_double_after_split",
    "can_hit_split_aces",
    "can_resplit",
    "can_split_hand",
    "can_split_initial_hand",
    "card_value",
    "cards_remaining",
    "compare_true_count",
    "counting_summary",
    "deal_initial_hand",
    "decks_remaining",
    "default_history_dir",
    "describe_rule_profile",
    "draw_card",
    "ensure_history_dir",
    "evaluate_hand",
    "explain_action",
    "explain_decision_factors",
    "explain_insurance_no",
    "explain_split_rules",
    "explain_state",
    "find_matching_deviation",
    "format_cards",
    "format_header",
    "format_kv",
    "format_list",
    "format_percentage",
    "format_result_status",
    "format_section",
    "format_warning",
    "generate_strategy_question",
    "get_profile",
    "get_rule_profile",
    "grade_strategy_answer",
    "hilo_value",
    "is_ace_pair",
    "is_counting_allowed_context",
    "is_pair_hand",
    "list_rule_profiles",
    "list_session_records",
    "load_session_record",
    "normalize_rank",
    "normalize_true_count",
    "normalize_user_action",
    "normalize_profile_key",
    "penetration",
    "play_dealer_hand",
    "play_split_subhand",
    "play_training_hand",
    "profile_supports_das",
    "profile_supports_hit_split_aces",
    "profile_supports_resplit",
    "profile_supports_surrender",
    "recommend",
    "recommend_with_deviation",
    "resolve_outcome",
    "run_count_session",
    "run_strategy_session",
    "save_session_record",
    "should_take_insurance",
    "shuffle_shoe",
    "simulate_training_hand",
    "split_initial_hand",
    "summarize_history",
    "true_count",
    "update_running_count",
    "update_running_count_many",
    "validate_decks",
]
